name: ci-main

on:
 push:
  branches:
   - master


jobs:
 build:
    runs-on: ["self-hosted", "X64", "default"]
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    #timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - name: Prep
        id: prep
        run: |
          GIT_BRANCH=${GITHUB_REF##*/}
          # Set the platforms to build for here and thus reduce duplicating it.
          PLATFORMS=amd64,arm64
          TAGS="ghcr.io/${{ github.repository_owner }}/lynxchan:${GIT_BRANCH}"

          # Set output parameters.

          if [ "${{github.event_name}}" == "pull_request" ]; then
            echo ::set-output name=push::false
          else
            echo ::set-output name=push::true
            echo ::set-output name=tags::${TAGS}
            echo ::set-output name=branch::${GIT_BRANCH}
            echo ::set-output name=docker_image::${DOCKER_IMAGE}
          fi
          echo ::set-output name=platforms::${PLATFORMS}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
        with:
         platform: ${{ steps.prep.outputs.platforms }}
         
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
        with:
         install: true
         version: latest
         driver-opts: image=moby/buildkit:latest
        
      - name: prepare variables
        uses: ./.github/actions/docker-push-variables
        id: ev
     
      - name: Building Docker Image
        uses: docker/build-push-action@v3
        with:
          push: ${{ steps.ev.outputs.shouldBuild == 'true' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/lynxchan:gh-${{ steps.ev.outputs.branchNameContainer }}
            ghcr.io/${{ github.repository_owner }}/lynxchan:gh-${{ steps.ev.outputs.branchNameContainer }}-${{ steps.ev.outputs.timestamp }}-${{ steps.ev.outputs.sha }}
          build-args: |
            GIT_BUILD_HASH=${{ steps.ev.outputs.sha }}
          platforms: ${{ steps.prep.outputs.platforms }}
